name: Frontend Docker Build

on:
  push:
    branches:
      - "**"

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check start directory
        run: pwd


      - name: Install deps
        working-directory: react-client-app
        run:  cd front-end/react-client-app && npm i

      - name: Build frontend
        working-directory: react-client-app
        run: npm run build

      - name: Build Docker image
        run: docker build -t cms-frontend -f front-end/Dockerfile .
