server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        index index.html index.htm;
        # Essential for React Router: redirects all requests to index.html
        try_files $uri $uri/ /index.html;
    }

      # Explicitly handle Vite's /assets folder
    location /assets/ {
        # Browsers can cache these heavily because Vite hashes the filenames
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Optional: Cache static assets like JS and CSS
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}
