// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table user {
  id uuid [primary key]
  firstName varchar
  lastName varchar
  account uuid
  age integer
  email varchar
  password varchar
}
