// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table user {
  id uuid [pk]
  firstName varchar
  lastName varchar
  account uuid [unique]
  age integer
  email varchar
  password varchar
}
